spring.application.name=swiftbus-service
server.port=${PORT:8080}

# ---------------------------
# DataSource / PostgreSQL
# ---------------------------

spring.datasource.url=jdbc:postgresql://caboose.proxy.rlwy.net:55261/railway
spring.datasource.username=postgres
spring.datasource.password=BRXcrmFcXrxBkONfDxrXFIKQyLgGjJGU
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------
# JPA / Hibernate
# ---------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ---------------------------
# Swagger / OpenAPI
# ---------------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
